### ISSUE TITLE
Command to remove all tv series

### ISSUE THREAD

**Issue by kiam001** [David-Moreira/JellyseerrSync#10]
i have added the sonarr notify url and it works fine, however it does not remove any leftovers as there is only a movie sync function but no tv sync function.

**Comment by kiam001** [comment]
I fixed the problem a bit "dirty" by deleting jellyseer db

jellyseerr/config/db$ ls
db.sqlite3  db.sqlite3-shm  db.sqlite3-wal

this files deleted and start software again

**Comment by David-Moreira** [comment]
Hey @kiam001 
Yea, If I remember correctly, there was some limitation, or at least I could not find the correct exposed apis to get the required data to proceed with the **full** tv sync.

Anyway it is of note that jellyseerr is working on this feature and it is mostly ready from what I can tell, https://github.com/Fallenbagel/jellyseerr/pull/522 Hopefully it will be out soon this year, so I haven't really been improving this further.

I have been using this workaround since I published. I think I have seen a tv series that has failed to sync here and there, movies seem to always sync fine. 
So it's been working well enough for me as a temporary workaround until jellyseerr supports this.

**Comment by David-Moreira** [comment]
With the release of jellyseer v1.8.0 https://github.com/Fallenbagel/jellyseerr/releases/tag/v1.8.0 a feature was implemented to properly remove media automatically on scan : https://github.com/Fallenbagel/jellyseerr/pull/522
This means that this repository / application should no longer be needed from jellyseerr v1.8.0+. 
This repository will no longer have updates and in a few days it'll be archived. All the docker images will still be available for usage.
Closing issue,
